#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${FRAMEBENCH_BUILD_VENV:-${FILM_MASTER_BUILD_VENV:-"$ROOT_DIR/.runtime/pyinstaller-venv"}}"
BUILD_PYTHON="${FRAMEBENCH_BUILD_PYTHON:-${FILM_MASTER_BUILD_PYTHON:-}}"
BUILD_DIR="$ROOT_DIR/.runtime/pyinstaller"
RUNTIME_DIR="$ROOT_DIR/frontend/backend-runtime"
BACKEND_OUT_DIR="$RUNTIME_DIR/backend"
BIN_OUT_DIR="$RUNTIME_DIR/bin"
BACKEND_BINARY_NAME="framebench-backend"
PYINSTALLER_DATA_SEP=":"

if [[ -z "$BUILD_PYTHON" ]]; then
  if command -v python3.11 >/dev/null 2>&1; then
    BUILD_PYTHON="$(command -v python3.11)"
  else
    BUILD_PYTHON="$(command -v python3)"
  fi
fi

if ! "$BUILD_PYTHON" -c 'import sys; raise SystemExit(sys.version_info < (3, 10))'; then
  echo "Backend packaging requires Python 3.10 or newer: $BUILD_PYTHON" >&2
  exit 1
fi

if [[ "$(uname -s)" == "MINGW"* || "$(uname -s)" == "MSYS"* || "$(uname -s)" == "CYGWIN"* ]]; then
  BACKEND_BINARY_NAME="framebench-backend.exe"
  PYINSTALLER_DATA_SEP=";"
fi

resolve_tool() {
  local env_name="$1"
  local binary_name="$2"
  local node_package="${3:-}"
  local legacy_env_name="${4:-}"
  local env_value="${!env_name:-}"
  if [[ -z "$env_value" && -n "$legacy_env_name" ]]; then
    env_value="${!legacy_env_name:-}"
  fi

  if [[ -n "$env_value" ]]; then
    if [[ ! -x "$env_value" ]]; then
      echo "$env_name points to a non-executable path: $env_value" >&2
      return 1
    fi
    printf '%s\n' "$env_value"
    return 0
  fi

  if [[ -n "$node_package" ]] && command -v node >/dev/null 2>&1; then
    local node_path
    node_path="$(
      cd "$ROOT_DIR/frontend"
      node - "$node_package" <<'NODE'
const packageName = process.argv[2]
try {
  const value = require(packageName)
  const candidate = typeof value === "string" ? value : value && value.path
  if (candidate) process.stdout.write(candidate)
} catch {}
NODE
    )"
    if [[ -n "$node_path" && -x "$node_path" ]]; then
      printf '%s\n' "$node_path"
      return 0
    fi
  fi

  if command -v "$binary_name" >/dev/null 2>&1; then
    command -v "$binary_name"
    return 0
  fi

  echo "Missing required tool: $binary_name. Install $node_package, install $binary_name, or set $env_name." >&2
  return 1
}

copy_tool() {
  local source_path="$1"
  local target_name="$2"
  local target_path="$BIN_OUT_DIR/$target_name"

  cp "$source_path" "$target_path"
  chmod +x "$target_path"

  if [[ "$(uname -s)" == "Darwin" ]] && command -v otool >/dev/null 2>&1; then
    if otool -L "$source_path" | grep -E "/opt/homebrew|/usr/local/Cellar" >/dev/null 2>&1; then
      echo "Warning: $target_name is dynamically linked to Homebrew libraries. Verify the DMG on a clean Mac." >&2
    fi
  fi
}

echo "Preparing backend runtime build environment..."
BUILD_PYTHON_VERSION="$("$BUILD_PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
if [[ -x "$VENV_DIR/bin/python" ]]; then
  VENV_PYTHON_VERSION="$("$VENV_DIR/bin/python" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  if [[ "$VENV_PYTHON_VERSION" != "$BUILD_PYTHON_VERSION" ]]; then
    rm -rf "$VENV_DIR"
  fi
fi
echo "Using Python $BUILD_PYTHON_VERSION: $BUILD_PYTHON"
"$BUILD_PYTHON" -m venv "$VENV_DIR"
"$VENV_DIR/bin/python" -m pip install --upgrade pip setuptools wheel
"$VENV_DIR/bin/python" -m pip install -r "$ROOT_DIR/backend/requirements.txt" pyinstaller

rm -rf "$BUILD_DIR" "$RUNTIME_DIR"
mkdir -p "$BUILD_DIR" "$BACKEND_OUT_DIR" "$BIN_OUT_DIR"

echo "Building backend executable..."
"$VENV_DIR/bin/python" -m PyInstaller \
  --clean \
  --noconfirm \
  --onedir \
  --name "$BACKEND_BINARY_NAME" \
  --distpath "$BUILD_DIR/dist" \
  --workpath "$BUILD_DIR/work" \
  --specpath "$BUILD_DIR/spec" \
  --paths "$ROOT_DIR" \
  --add-data "$ROOT_DIR/backend/prompts${PYINSTALLER_DATA_SEP}backend/prompts" \
  --collect-all whisper \
  --collect-all tiktoken \
  --collect-submodules uvicorn \
  --collect-submodules fastapi \
  --collect-submodules sqlalchemy \
  --collect-submodules aiosqlite \
  --hidden-import uvicorn.logging \
  --hidden-import uvicorn.loops.auto \
  --hidden-import uvicorn.protocols.http.auto \
  --hidden-import uvicorn.protocols.websockets.auto \
  --hidden-import uvicorn.lifespan.on \
  "$ROOT_DIR/backend/runtime_server.py"

cp -R "$BUILD_DIR/dist/$BACKEND_BINARY_NAME/." "$BACKEND_OUT_DIR/"
chmod +x "$BACKEND_OUT_DIR/$BACKEND_BINARY_NAME"

echo "Copying media tools..."
FFMPEG_SOURCE="$(resolve_tool FRAMEBENCH_FFMPEG_BIN ffmpeg ffmpeg-static FILM_MASTER_FFMPEG_BIN)"
FFPROBE_SOURCE="$(resolve_tool FRAMEBENCH_FFPROBE_BIN ffprobe ffprobe-static FILM_MASTER_FFPROBE_BIN)"
copy_tool "$FFMPEG_SOURCE" ffmpeg
copy_tool "$FFPROBE_SOURCE" ffprobe

cat > "$RUNTIME_DIR/README.txt" <<EOF
Framebench backend runtime

Generated by scripts/build_backend_runtime.sh.

Contents:
- backend/$BACKEND_BINARY_NAME
- backend/_internal/ (Python runtime and bundled libraries)
- bin/ffmpeg
- bin/ffprobe

Electron starts the backend executable directly in production builds and passes
FRAMEBENCH_DATA_DIR, FRAMEBENCH_LOCAL_TOKEN, FRAMEBENCH_BACKEND_PORT,
FRAMEBENCH_FFMPEG_BIN, and FRAMEBENCH_FFPROBE_BIN at runtime. Legacy
FILM_MASTER_* environment variables are still accepted for compatibility.
EOF

echo "Backend runtime ready: $RUNTIME_DIR"
